import Link from 'next/link';
import "./globals.css";
import "./quiosco.css";
import { Josefin_Sans } from 'next/font/google'
import { Noto_Sans_KR } from 'next/font/google'
import Logo from '@/components/Logo';
import Menus from '@/components/Menus';
import CopyInfo from '@/components/CopyInfo';
import Canvas from '@/components/Canvas';
import MobileHeader from '@/components/MobileHeader';

// 영어용 폰트
const josefin = Josefin_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-josefin',
})

// 한글용 폰트
const notoSansKr = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-noto-sans-kr',
})

export const metadata = {
  title: "QUIOSCO 2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={`${josefin.variable} ${notoSansKr.variable}`}>
      <body className='relative'>
        <Canvas />
        <MobileHeader />
        <Logo />
        <Menus />
        {children}
        <CopyInfo />
      </body>
    </html>
  );
}
